// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Beehive: typeof import('./src/components/content/beehive/Beehive.vue')['default']
    CircleChart: typeof import('./src/components/content/circlechart/CircleChart.vue')['default']
    ContentBackground: typeof import('./src/components/content/background/ContentBackground.vue')['default']
    Cube: typeof import('./src/components/content/animation/Cube.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    LineChart: typeof import('./src/components/content/linechart/LineChart.vue')['default']
    NavBar: typeof import('./src/components/content/navbar/NavBar.vue')['default']
    Progress: typeof import('./src/components/content/progress/Progress.vue')['default']
    TimeLine: typeof import('./src/components/content/timeline/TimeLine.vue')['default']
    ToDoList: typeof import('./src/components/content/todolist/ToDoList.vue')['default']
    TopBackGround: typeof import('./src/components/content/background/TopBackGround.vue')['default']
    WeekTodo: typeof import('./src/components/content/weektodo/WeekTodo.vue')['default']
    Windmill: typeof import('./src/components/content/animation/Windmill.vue')['default']
  }
}

export { }
